//! Development-only generator; not linked into the gateway binary.
use std::{fmt::Write as _, fs, path::PathBuf};

use anyhow::Result;
use estuary::config::{
    AnthropicProtocol, CircuitBreakerConfig, HealthConfig, ModelCapabilityConfig, ModelFamily,
    NodeConfig, PrefixConfig, ProviderConfig, ProviderKind, RetryConfig, RoutingConfig,
    ServerConfig, Settings, VllmKvEventsConfig,
    contract::{
        NodeValidationRule, RESERVED_UPSTREAM_HEADERS, RuleCondition, RuleKind,
        editor_node_defaults, node_validation_rules,
    },
};
use serde::Serialize;
use ts_rs::{Config, TS};

#[derive(Serialize, TS)]
struct ConfigDefaults {
    node: NodeConfig,
    editor: NodeConfig,
    capability: ModelCapabilityConfig,
    kv_events: VllmKvEventsConfig,
}

fn main() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out = std::env::args_os()
        .nth(1)
        .map_or_else(|| root.join("web/src/generated"), PathBuf::from);
    fs::create_dir_all(&out)?;
    let config = Config::new().with_large_int("number");
    let mut types = String::from(
        "// Generated by cargo run --features config-contract --example config_contract. Do not edit.\n\n",
    );
    macro_rules! export {
        ($($ty:ty),+ $(,)?) => { $(writeln!(types, "export {}\n", <$ty>::decl(&config))?;)+ };
    }
    export!(
        Settings,
        ServerConfig,
        RoutingConfig,
        PrefixConfig,
        HealthConfig,
        CircuitBreakerConfig,
        RetryConfig,
        NodeConfig,
        ProviderConfig,
        ModelCapabilityConfig,
        ModelFamily,
        ProviderKind,
        AnthropicProtocol,
        VllmKvEventsConfig,
        RuleCondition,
        RuleKind,
        NodeValidationRule,
        ConfigDefaults
    );
    fs::write(out.join("config.ts"), types)?;
    let defaults = ConfigDefaults {
        node: NodeConfig::default(),
        editor: editor_node_defaults(),
        capability: ModelCapabilityConfig::default(),
        kv_events: VllmKvEventsConfig::default(),
    };
    fs::write(
        out.join("config-defaults.json"),
        serde_json::to_string_pretty(&defaults)? + "\n",
    )?;
    fs::write(
        out.join("config-rules.json"),
        serde_json::to_string_pretty(&node_validation_rules())? + "\n",
    )?;
    fs::write(
        out.join("reserved-headers.json"),
        serde_json::to_string_pretty(RESERVED_UPSTREAM_HEADERS)? + "\n",
    )?;
    Ok(())
}
